### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by jayvdb** [msabramo/python_unittest_parameterized_test_case#5]
It is really helpful to have a LICENSE file in the repository - it makes it clearer , and the license text usually refers to a Copyright line which is contained in that file, and is custom for each project.

It is also expected for distro packaging.

**Comment by jayvdb** [comment]
See https://build.opensuse.org/request/show/835458

**Comment by msabramo** [comment]
Closed by #6. Thanks, @jayvdb!
